language: node_js

node_js:
  - 8
before_install:
 - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

install:
  - npm install
  - npm run bootstrap -- --ci 

script:
  - npm run build 

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run publish -- --canary

